name: Deploy NestJS App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v2

      - name: Set up SSH for private repo access
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Log in to GitHub Docker Registry
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/lordkode/test_blog:latest

      - name: Tag and push to GitHub Container Registry
        run: |
          docker tag ghcr.io/lordkode/test_blog:latest ghcr.io/lordkode/test_blog:${{ github.sha }}
          docker push ghcr.io/lordkode/test_blog:latest
          docker push ghcr.io/lordkode/test_blog:${{ github.sha }}

      - name: Tag and push to Docker Hub
        run: |
          docker tag ghcr.io/lordkode/test_blog:latest your-dockerhub-username/test_blog:latest
          docker tag ghcr.io/lordkode/test_blog:latest your-dockerhub-username/test_blog:${{ github.sha }}
          docker push your-dockerhub-username/test_blog:latest
          docker push your-dockerhub-username/test_blog:${{ github.sha }}

      - name: Add private repo as remote
        run: |
          git remote add private git@github.com:EpitechCodingAcademyPromo2024/C-COD-250-COT-2-3-showtime-richard.ati.git
          git push private master
