name: Deploy NestJS App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v2

      - name: Set up SSH for private repo access
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/lordkode/showtime:latest

      - name: Tag and push to Docker Hub
        run: |
          docker tag ghcr.io/lordkode/showtime:latest devrichard2001/showtime:latest
          docker tag ghcr.io/lordkode/showtime:latest devrichard2001/showtime:${{ github.sha }}
          docker push devrichard2001/showtime:latest
          docker push devrichard2001/showtime:${{ github.sha }}

      - name: Add private repo as remote
        run: |
          git remote add private git@github.com:EpitechCodingAcademyPromo2024/C-COD-250-COT-2-3-showtime-richard.ati.git
          git config --global user.email "richard.ati@epitech.eu"
          git config --global user.name "Lordkode"

      - name: Clean up git objects
        run: |
          git gc --prune=now
          git repack -a -d --depth=250 --window=250

      - name: Force push to private repo
        run: |
          git fetch private
          git reset --hard origin/master
          git push private master --force
